### ISSUE TITLE
Api Access 

### ISSUE THREAD

**Issue by testbotgt** [openclarity/kubeclarity#173]
I access the kubeclarity api address that I set up in the kubernetes environment through the 8888 port and I am getting 404 when trying to access the paths according to the swagger directive.

**Comment by FrimIdan** [comment]
port 8080 is the backend/api port - please try to use it.
```
  ports:
  - name: backend
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: runtime-scan-results
    port: 8888
    protocol: TCP
    targetPort: 8888
```

**Comment by testbotgt** [comment]
```
kind: Service
apiVersion: v1
metadata:
  name: kst-kubeclarity
  namespace: kubeclarity
  labels:
    app.kubernetes.io/instance: kst
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kst-kubeclarity
    helm.sh/chart: kubeclarity-v2.2.0
  annotations:
    helm.sh/hook: pre-install
spec:
  ports:
    - name: backend
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30421
    - name: runtime-scan-results
      protocol: TCP
      port: 8888
      targetPort: 8888
      nodePort: 30754
  selector:
    app: kst-kubeclarity
  clusterIP: 10.233.33.182
  type: LoadBalancer
  sessionAffinity: None
  externalTrafficPolicy: Cluster
```

I don't see any problem in my service configuration. Access <ip>:8888
I get 404 not found on my first access. When I send a request to the paths in swagger.yml, I get 404 in the same way.
