### ISSUE TITLE
Execute scanner jobs in kubeclarity's namespace rather than in originating pod's, or allow setting custom tolerations

### ISSUE THREAD

**Issue by log2** [openclarity/kubeclarity#183]
**Is your feature request related to a problem? Please describe.**
Currently, Kubeclarity schedules scanner jobs in the same namespace as the targeted pod's.

While this is crucial for images hosted in private repositories, since this allows [setting a secretKeyRef which just works](https://github.com/openclarity/kubeclarity/blob/main/runtime_scan/pkg/scanner/job_managment.go#L312) (both originating pod and scanner job/pod execute in the same namespace), it may become an hurdle to execute scanner job/pod in namespaces which requires tolerations to be added in order for the scheduling to succeed.

As an example, on Azure (AKS) clusters, some namespaces such as calico-system, kube-system and so on have all or most of their workloads  managed by k8s-addon manager, which in turn adds the following toleration:

```yaml
- key: CriticalAddonsOnly
  operator: Exists
```

The latter is required in order to allow to execute pods even when EVERY node in ALL nodegroups is tainted somehow, but at least some nodes (e.g., so-called AKS "system" nodes) are tainted with `CriticalAddonsOnly`.

However, when Kubeclarity schedules scanner job/pods on such namespaces AND all nodes are tainted (possibly with different taints), pod remains stuck in pending state due to lack of adequate tolerations.

**Describe the solution you'd like**

I foresee two solutions:
- a partial solution is to schedule all jobs/pods NOT requiring access to a private repository to kubeclarity namespace, since in that namespace one can apply policies from kyverno's or something alike, in order to add the tolerations needed (in fact, that's we already do in our clusters to enable scheduling of kubeclarity's core pods)
- a full solution requires adding at least custom tolerations to all job/pods, so that during installation of kubeclarity one can explicitly mention a set of minimum tolerations that allow proper scheduling (such as the abovementioned CriticalAddonsOnly). 
   
**Describe alternatives you've considered**
Using [this feature](https://github.com/openclarity/kubeclarity/pull/180) and adding labels (which, in turn, trigger application of policies to add the tolerations needed) to all possible namespaces could be useful for some namespaces, but for kube-system it shouldn't be enough, since most policy engine, such as Kyverno, do not operate on kube-system by default (and for good reasons, most likely).

Thus custom labels couldn't be enough for scheduling, while remaining useful to tag kubeclarity job/pods.

**Additional context**
None

**Comment by FrimIdan** [comment]
Hi @log2 thank you for the detailed issue report.
I think we can easily support the full solution, if I understand correctly we should add for the scanner pod spec an option to configure `tolerations`.

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubeclarity.name" . }}-scanner-template
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{ include "kubeclarity.labels" . }}
data:
  config: |-
    apiVersion: batch/v1
    kind: Job
    metadata:
      labels:
{{- toYaml (index .Values "kubeclarity-runtime-scan" "labels") | nindent 8 }}
    spec:
      backoffLimit: 0
      ttlSecondsAfterFinished: 300
      template:
        metadata:
          labels:
{{- toYaml (index .Values "kubeclarity-runtime-scan" "labels") | nindent 12 }}
        spec:
          tolerations:                                    <--- tolerations section should be configurable in helm values file
          - key: "CriticalAddonsOnly"
            operator: "Exists"
          restartPolicy: Never
          volumes:
.
.
.
```
