### ISSUE TITLE
Can we integrate trivy here for image scanning?

### ISSUE THREAD

**Issue by sarath-s-kumar** [openclarity/kubeclarity#248]
Hei
Can we integrate trivy for image vulnerability scanning?

**Comment by akpsgit** [comment]
Hi @sarath-s-kumar, sure! We actually had this on the roadmap for a while and now it's a good time to start. We're on it. thanks :)

**Comment by sambetts-cisco** [comment]
PR #252 is the first step for trivy integration adding support for trivy as an SBOM analyzer, the next steps are to add it as a vul scanner too.

**Comment by akpsgit** [comment]
@sarath-s-kumar  Done :) Thanks a lot!

**Comment by sarath-s-kumar** [comment]
@akpsgit Is the code changes in the same PR?

**Comment by sambetts-cisco** [comment]
Hi @sarath-s-kumar, vul support was added in this PR: https://github.com/openclarity/kubeclarity/pull/258

**Comment by sarath-s-kumar** [comment]
what is the configuration changes required  for using trivy as vulnerability scanner and sbom in the helm chart(values.yaml)?

**Comment by sarath-s-kumar** [comment]
Reasons: failed to analyze image: failed to run job manager: 1 error occurred: * "trivy" job failed: failed to generate SBOM: init error: cache error: unable to initialize the cache: unable to initialize fs cache: failed to create cache dir: mkdir /.cache: read-only file system 

@akpsgit @sambetts-cisco 

Note:- I enabled flags for trivy in the values.yaml

**Comment by sambetts-cisco** [comment]
Hi @sarath-s-kumar can you please open a new ticket for this bug, and attach the contents of the kubeclarity `<helm release name>-scanner-template` config map, and the helm values.yaml kubeclarity-runtime-scan section. The scanner should be configured to create the cache in /tmp through an environment variable so there might be an issue in the helm templating or in the code reading the variable we'll need to investigate.

**Comment by sambetts-cisco** [comment]
Just tested with the latest code from main and trivy enabled, values.yaml looks like:
```
     ## Analyzer config.
     analyzer:
       ## Space seperated list of analyzers. (syft gomod)
       analyzerList: "syft gomod trivy"

       analyzerScope: "squashed"

       trivy:
         ## Enable trivy scanner, if true make sure to add it to analyzerList above
         ##
         enabled: true
         timeout: "300"

     ## Scanner config.
     scanner:
       ## Space seperated list of scanners. (grype dependency-track)
       scannerList: "grype trivy"

       grype:
         ## Enable grype scanner, if true make sure to add it to scannerList above
         ##
         enabled: true
         ## Grype scanner mode. (LOCAL, REMOTE)
         mode: "REMOTE"

         ## Remote grype scanner config.
         remote-grype:
           timeout: "2m"

       dependency-track:
         ## Enable dependency-track scanner, if true make sure to add it to scannerList above
         ##
         enabled: false
         insecureSkipVerify: "true"
         disableTls: "true"
         apiserverAddress: "dependency-track-apiserver.dependency-track"
         apiKey: ""

       trivy:
         ## Enable trivy scanner, if true make sure to add it to scannerList above.
         ## To guarentee reliable scans, also ensure that the trivy analyzer is enabled.
         ##
         enabled: trivy
         timeout: "300"
```
The SBOM and Vul scans are working as expected and are reporting to the UI correctly.
