### ISSUE TITLE
How to configure values.yaml for external database usage?

### ISSUE THREAD

**Issue by John-Levi0909** [openclarity/kubeclarity#269]
When I deploy other microservices using helm-charts, there's usually an option to use an external database for persistence volume claims in PostgreSQL. I'm quite new to some of the helm concepts and I'm not really sure if this is necessary but I'd like to ask anyway. I cannot find instructions regarding this problem and it would be helpful if anyone could explain the configs needed for the initdb. I'm looking for clarification if I should set the values.yaml to something like this: 

<img width="277" alt="image" src="https://user-images.githubusercontent.com/117496581/205433309-d8c8434b-5051-41fa-9b41-49641237a83e.png">

Thanks!

**Comment by FrimIdan** [comment]
Hi @John-Levi0909 , KubeClarity is using [bitnami postgresql](https://github.com/bitnami/charts/blob/main/bitnami/postgresql/README.md) as a [dependecy](https://github.com/openclarity/kubeclarity/blob/main/charts/kubeclarity/Chart.yaml#L14-L19).

You can configure the postgresql per the bitnami [documentation](https://github.com/bitnami/charts/blob/main/bitnami/postgresql/README.md) in kubeclarity values.yaml under [kubeclarity-postgresql section](https://github.com/openclarity/kubeclarity/blob/main/charts/kubeclarity/values.yaml#L227).

**Comment by maxboaventura** [comment]
Hi @John-Levi0909,
That's how you can do it. One single Kubeclarity instance will be able to see data from many clusters.
In my view it doesn't seen to be the priority of this project and honestly, I'm curious to see how long Cisco can support a Opensource team/initiative internally.

On the global section create parameters for the database:
```
global:
  ## Database
  ##
  databaseHost: yourDBhostname
  databasePassword: xxxxxx
```
change the deployment template and replace the value of this parameter
```
            - name: DB_HOST
              value: "{{  .Values.global.databaseHost }}"
```

**Comment by John-Levi0909** [comment]
> Hi @John-Levi0909, That's how you can do it. One single Kubeclarity instance will be able to see data from many clusters. In my view it doesn't seen to be the priority of this project and honestly, I'm curious to see how long Cisco can support a Opensource team/initiative internally.
> 
> On the global section create parameters for the database:
> 
> ```
> global:
>   ## Database
>   ##
>   databaseHost: yourDBhostname
>   databasePassword: xxxxxx
> ```
> 
> change the deployment template and replace the value of this parameter
> 
> ```
>             - name: DB_HOST
>               value: "{{  .Values.global.databaseHost }}"
> ```

I can't seem to locate the deployment template on the helm structure. Perhaps is there an alternative way to set an external database? I'm using an AWS RDS and I'm not sure which config to put the host name. Thank you!

**Comment by sambetts-cisco** [comment]
This pull request https://github.com/openclarity/kubeclarity/pull/277 added the option into the helm chart for external database configuration. If you set kubeclarity-postgresql.enabled = false, and then configure this new section you'll be able to connect to an external postgres server:

```
# Use kubeclarity-postgresql-external if you want to reach an already existing PostgreSQL instance
kubeclarity-postgresql-external:
  enabled: false
  auth:
    existingSecret: kubeclarity-postgresql-secret
    username: kubeclarity
    host: pgsql.hostname  # replace this to reach your PostgreSQL instance
    port: 5432
    database: kubeclarity
```

@John-Levi0909 Does this solve the use case you had? If so then can we please close this issue?
