### ISSUE TITLE
Getting error /build/backend/pkg/database/scheduler.go:58 record not found

### ISSUE THREAD

**Issue by AshutoshAM2002** [openclarity/kubeclarity#466]
#### What happened:
I encountered an issue while trying to install kubeclarity on an EKS (Elastic Kubernetes Service) cluster using the provided Helm chart. The error occurs when checking the logs of the pod, and it results in a "webpage not found" message when attempting to access the application.

Error:
**/build/backend/pkg/database/scheduler.go:58 record not found**

#### Anything else we need to know?:
My helm values.yaml file:
```yaml
kubeclarity:
  resources:
    limits:
      memory: "500Mi"
      cpu: "200m"
    requests:
      memory: "200Mi"
      cpu: "100m"

  podAnnotations:
    co.elastic.logs/enabled: "true"

# Be careful when using ingress. As there is no authentication on Kubeclarity yet, your instance may be accessible.
# Make sure the ingress remains internal if you decide to enable it.
  ingress:
    enabled: true
    labels: {}
    annotations: 
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/group.name: ingress
      alb.ingress.kubernetes.io/load-balancer-name: kubeclarity
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/scheme: internal
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'

    hosts:
      - host: kubeclarity.clouddrove.ca
        paths: []
    tls: [] 
```
Also tried using external database.

**Comment by FrimIdan** [comment]
@AshutoshAM2002 thanks for the report.
Can you describe and add some screenshots for the web server logic process? (port forwarding command, URL in the browser) 
I'm not sure that the error that you've attached is related to a `webpage not found` message.

**Comment by AshutoshAM2002** [comment]
I have used the default chart with the above override-values.yaml
the chart is creating the following resources on my AWS EKS cluster-
PVC of PostgreSQL
kubeclarity pod (webserver)
kubeclarity-grype-server
kubeclarity-postgresql pod
kubeclarity-sbom-db pod

Logs of each pod is given below -
'''
kubeclarity (webserver)
Defaulted container "kubeclarity" out of: kubeclarity, kubeclarity-kubeclarity-wait-for-pg-db (init), kubeclarity-kubeclarity-wait-for-sbom-db (init), kubeclarity-kubeclarity-wait-for-grype-server (init)

2023/07/20 15:49:37 /build/backend/pkg/database/scheduler.go:58 record not found
[82.992ms] [rows:0] SELECT * FROM "scheduler" ORDER BY "scheduler®."id" LIMIT 1
2 10 po 1/20 15:49:37 Serving kube clarity runtime scan a p is at http://[::]:8888
2 °7%./20 15:49:37 Serving kube clarity a p is at http://[::]:8080
-----------------
kubeclarity-grype-server
2023/07/20 15:49:29 Serving grype server at http://[
-----------------
kubeclarity-postgresql 
postgresql 15:49:16.72

postgresql Welcome to the Bitnami postgresql container
postgresql 15:49:16.72 Subscribe to project updates by watching http:
postgresql 15:49:16.72 Submit issues and feature requests at https:
postgresql 15:49:16.73

postgresql 15:49:16.74 INFO ==> ** Starting PostgreSQL setup **
postgresql INFO ==> Validating settings in POSTGRESQL * env vars..
postgresql 15:49:16.77 INFO ==> Loading custom pre-init scripts.
postgresql 15:49:16.78 INFO ==> Initializing PostgresqL database
postgresql 15:49:16.80 INFO ==> pg_hba.conf file not detected. Generating it...
postgresql 15:49:16.80 INFO ==> Generating local authentication configuration
postgresql 15:49:17.93 INFO ==> Starting PostgreSQL in background...

postgresql 15:49:18.14 INFO ==> Changing password of postgres

postgresql 15:49:18.19 INFO ==> Configuring replication parameters

postgresql INFO ==> Configuring synchronous replication

postgresql 15:49:18.27 INFO ==> Configuring fsync
postgresql 15:49:18.3 INFO ==> Stopping PostgresQL...
waiting for server to shut down.... done

server stopped

postgresql 15:49:18.48 INFO ==> Loading custom scripts
postgresql 15:49:18.49 INFO ==> Enabling remote connections
postgresql 15:49:18.51 INFO ==> ** PostgresQL setup finished! **

/github.com/bitnami/containers
/github.com/bitnami/containers/issues

postgresql 15:49:18.53 INFO ==> ** Starting PostgreSQL **
2023-07-20 15:49:18.554 GMT [1] LOG: pgaudit extension initialized

2023-07-20 15:49:18.564 GMT starting PostgreSQL 14.6 on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
2023-07-20 15:49:18.565 GMT listening on IPv4 address "0.0.6.0", port 5432

2023-07-20 GMT. listening on IPv6 address , port 5432

2023-07-20 15:49:18.582 GMT listening on Unix socket "/tmp/.s.PGSQL.5432"

2023-07-20 15:49:18.592 GMT database system was shut down at 2023-07-20 15:49:18 GMT

2023-07-20 15:49:18.601 GMT database system is ready to accept connections
'''
I'm assuming that because of this 2023/07/20 15:49:37 /build/backend/pkg/database/scheduler.go:58 record not found error line in kubeclarity webserver-pod I'm not able to access webpage on Browser

**Comment by FrimIdan** [comment]
@AshutoshAM2002 can you share the port forwarding command and the URL in the browser to tried? screenshot will also help.
The `record not found` shouldn't be related.

**Comment by h1manshu98** [comment]
thanks @AshutoshAM2002 
setting up `port: 80` and `targetPort:8080` works for me and I'm able to access kubeclarity webpage via Load Balancer's DNS.

**Comment by FrimIdan** [comment]
@AshutoshAM2002 We can do it, you can also open a PR and we will approve it, but TBH not sure how it "solved" the issue?

**Comment by AshutoshAM2002** [comment]
Based on this documentation:
https://techblog.cisco.com/blog/kubeclarity-installation-on-aws-eks
I have configured a load balancer using the service:
```yaml
#values.yaml
  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
      service.beta.kubernetes.io/aws-load-balancer-name: "kubeclarity"
```
when you insert: 8080 in DNS means that your service is listening on port 8080
but port 80 is used when you don't insert any port in DNS,
as per this block:
```yaml
#template/service.yaml
kubeclarity:
  service:
    type: ClusterIP
    port: 80
    targetPort: 8080
    annotations: {}
```
the port is set to 80 which is the default port for any DNS,
But when you set port: 8080, you should specify DNS:8080 as well.

**Comment by AshutoshAM2002** [comment]
@FrimIdan I have made the changes in the /charts/kubeclarity/templates/service.yaml file in the new branch but cannot able to push the code getting "remote: Permission to openclarity/kubeclarity.git denied to AshutoshAM2002".
![Screenshot from 2023-08-01 00-15-41](https://github.com/openclarity/kubeclarity/assets/78293616/1173311b-d6ad-4c27-b674-7308dcc33dab)

Can you make the following changes to make the port dynamic:
```yaml
spec:
  type: {{ .Values.kubeclarity.service.type }}
  ports:
    - name: backend
      port: {{ .Values.kubeclarity.service.port }}
      protocol: TCP
      targetPort: {{ .Values.kubeclarity.service.targetPort }}
```
or give me permission to create and push in the new branch?
